
# MongoDB
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

logging.level.org.springframework.security=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=OFF