spring.application.name=planit
server.port=${PORT:8081}

jwt.secret=${JWT_SECRET:defaultsecretkey}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

allowCorsOrigin=${CORS:http://localhost:4200}


# Logging global
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO















