# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

# === MongoDB ===
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB:mydb}



# Debug léger
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=INFO